name: Extract and Upsert Gradle Plugins to Port

on:
  workflow_dispatch:
    inputs:
      gradle_path:
        description: "Path to the Gradle file"
        required: true
        default: ./build.gradle

jobs:
  update-port-plugins:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Extract Plugins from Gradle File
        id: parse-plugins
        env:
          GRADLE_PATH: ${{ github.event.inputs.gradle_path }}
        run: |
          python extract_gradle_plugins.py > plugins.json
          echo "plugins=$(cat plugins.json)" >> $GITHUB_OUTPUT

      - name: Bulk Upsert Plugins to Port
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: BULK_UPSERT
          entities: ${{ steps.parse-plugins.outputs.plugins }}
