name: Update Port Blueprints

on:
  workflow_dispatch:
    inputs:
      gradle_path:
        description: "Path to the Gradle file"
        required: true
        default: ./build.gradle

jobs:
  update-port-blueprints:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Extract Packages from Gradle File
        id: parse-packages
        env:
          GRADLE_PATH: ${{ github.event.inputs.gradle_path }}
        run: |
          python scripts/extract_gradle_packages.py > packages.json
          echo "::set-output name=packages::$(cat packages.json)"

      - name: Bulk Upsert Packages to Port
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.CLIENT_ID }}
          clientSecret: ${{ secrets.CLIENT_SECRET }}
          baseUrl: https://api.getport.io
          operation: BULK_UPSERT
          entities: ${{ steps.parse-packages.outputs.packages }}
